# 01 — EGFR Bioactivity Data Collection

## Project
Machine Learning-Guided Virtual Screening for EGFR Inhibitors

## Objective
Retrieve experimentally measured bioactivity data for compounds tested against human EGFR from the ChEMBL database.

## Why this matters
These experimentally characterized compounds will form the training dataset for a machine-learning QSAR model that predicts whether new compounds are likely to inhibit EGFR.

## Imports

In [1]:
import pandas as pd
import requests
from pathlib import Path

## Set up project paths

In [2]:
# Get the project root directory
PROJECT_ROOT = Path.cwd().parent

# Define data folders
RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"

# Make sure they exist
RAW_DATA_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("Raw data directory:", RAW_DATA_DIR)

Project root: /Users/gracescanlan/Desktop/egfr-ml-drug-discovery
Raw data directory: /Users/gracescanlan/Desktop/egfr-ml-drug-discovery/data/raw

## Test the ChEMBL API

In [3]:
BASE_URL = "https://www.ebi.ac.uk/chembl/api/data"

url = f"{BASE_URL}/target.json"

params = {
    "limit": 5
}

response = requests.get(url, params=params)

print("Status code:", response.status_code)

Status code: 200

## Search for EGFR

In [4]:
url = f"{BASE_URL}/target/search.json"

params = {
    "q": "epidermal growth factor receptor"
}

response = requests.get(url, params=params)

egfr_search = response.json()

In [5]:
egfr_search.keys()

dict_keys(['page_meta', 'targets'])

## Turn the search results into a table

In [6]:
targets_df = pd.DataFrame(egfr_search["targets"])

targets_df.head()

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Mus musculus,Epidermal growth factor receptor,33.0,False,CHEMBL3608,"[{'accession': 'Q01279', 'component_descriptio...",SINGLE PROTEIN,10090
1,[],Homo sapiens,Pro-epidermal growth factor,33.0,False,CHEMBL5734,"[{'accession': 'P01133', 'component_descriptio...",SINGLE PROTEIN,9606
2,[],Homo sapiens,Growth factor receptor-bound protein 7,31.0,False,CHEMBL1649051,"[{'accession': 'Q14451', 'component_descriptio...",SINGLE PROTEIN,9606
3,[],Homo sapiens,Delta and Notch-like epidermal growth factor-r...,30.0,False,CHEMBL5291567,"[{'accession': 'Q8NFT8', 'component_descriptio...",SINGLE PROTEIN,9606
4,[],Mus musculus,Protein cereblon/Epidermal growth factor receptor,30.0,False,CHEMBL6193842,"[{'accession': 'Q01279', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,10090

## Look at useful target information

In [8]:
targets_df.columns.tolist()

['cross_references',
 'organism',
 'pref_name',
 'score',
 'species_group_flag',
 'target_chembl_id',
 'target_components',
 'target_type',
 'tax_id']

In [9]:
targets_df[
    [
        "target_chembl_id",
        "pref_name",
        "target_type",
        "organism"
    ]
].head(20)

,target_chembl_id,pref_name,target_type,organism
0,CHEMBL3608,Epidermal growth factor receptor,SINGLE PROTEIN,Mus musculus
1,CHEMBL5734,Pro-epidermal growth factor,SINGLE PROTEIN,Homo sapiens
2,CHEMBL1649051,Growth factor receptor-bound protein 7,SINGLE PROTEIN,Homo sapiens
3,CHEMBL5291567,Delta and Notch-like epidermal growth factor-r...,SINGLE PROTEIN,Homo sapiens
4,CHEMBL6193842,Protein cereblon/Epidermal growth factor receptor,PROTEIN-PROTEIN INTERACTION,Mus musculus
5,CHEMBL203,Epidermal growth factor receptor,SINGLE PROTEIN,Homo sapiens
6,CHEMBL4295760,Epidermal growth factor receptor substrate 15,SINGLE PROTEIN,Homo sapiens
7,CHEMBL2363049,Epidermal growth factor receptor,PROTEIN FAMILY,Homo sapiens
8,CHEMBL3712972,Epidermal growth factor-like protein 7,SINGLE PROTEIN,Homo sapiens
9,CHEMBL3713025,Protein Cripto,SINGLE PROTEIN,Homo sapiens
10,CHEMBL4523680,Protein cereblon/Epidermal growth factor receptor,PROTEIN-PROTEIN INTERACTION,Homo sapiens
11,CHEMBL6193830,UBR/Epidermal growth factor receptor,PROTEIN-PROTEIN INTERACTION,Homo sapiens
12,CHEMBL6193841,Protein cereblon/Epidermal growth factor receptor,PROTEIN-PROTEIN INTERACTION,Mus musculus
13,CHEMBL3848,Receptor tyrosine-protein kinase erbB-2,SINGLE PROTEIN,Rattus norvegicus
14,CHEMBL2111431,Epidermal growth factor receptor and ErbB2 (HE...,PROTEIN FAMILY,Homo sapiens
15,CHEMBL3137284,MER intracellular domain/EGFR extracellular do...,CHIMERIC PROTEIN,Homo sapiens
16,CHEMBL4523747,EGFR/PPP1CA,PROTEIN-PROTEIN INTERACTION,Homo sapiens
17,CHEMBL4523998,von Hippel-Lindau disease tumor suppressor/Epi...,PROTEIN-PROTEIN INTERACTION,Homo sapiens
18,CHEMBL4802031,Baculoviral IAP repeat-containing protein 2/Ep...,PROTEIN-PROTEIN INTERACTION,Homo sapiens
19,CHEMBL5465557,CCN2-EGFR,PROTEIN-PROTEIN INTERACTION,Homo sapiens

In [10]:
human_egfr = targets_df[
    targets_df["organism"].eq("Homo sapiens")
][
    [
        "target_chembl_id",
        "pref_name",
        "target_type",
        "organism"
    ]
]

human_egfr

,target_chembl_id,pref_name,target_type,organism
1,CHEMBL5734,Pro-epidermal growth factor,SINGLE PROTEIN,Homo sapiens
2,CHEMBL1649051,Growth factor receptor-bound protein 7,SINGLE PROTEIN,Homo sapiens
3,CHEMBL5291567,Delta and Notch-like epidermal growth factor-r...,SINGLE PROTEIN,Homo sapiens
5,CHEMBL203,Epidermal growth factor receptor,SINGLE PROTEIN,Homo sapiens
6,CHEMBL4295760,Epidermal growth factor receptor substrate 15,SINGLE PROTEIN,Homo sapiens
7,CHEMBL2363049,Epidermal growth factor receptor,PROTEIN FAMILY,Homo sapiens
8,CHEMBL3712972,Epidermal growth factor-like protein 7,SINGLE PROTEIN,Homo sapiens
9,CHEMBL3713025,Protein Cripto,SINGLE PROTEIN,Homo sapiens
10,CHEMBL4523680,Protein cereblon/Epidermal growth factor receptor,PROTEIN-PROTEIN INTERACTION,Homo sapiens
11,CHEMBL6193830,UBR/Epidermal growth factor receptor,PROTEIN-PROTEIN INTERACTION,Homo sapiens
14,CHEMBL2111431,Epidermal growth factor receptor and ErbB2 (HE...,PROTEIN FAMILY,Homo sapiens
15,CHEMBL3137284,MER intracellular domain/EGFR extracellular do...,CHIMERIC PROTEIN,Homo sapiens
16,CHEMBL4523747,EGFR/PPP1CA,PROTEIN-PROTEIN INTERACTION,Homo sapiens
17,CHEMBL4523998,von Hippel-Lindau disease tumor suppressor/Epi...,PROTEIN-PROTEIN INTERACTION,Homo sapiens
18,CHEMBL4802031,Baculoviral IAP repeat-containing protein 2/Ep...,PROTEIN-PROTEIN INTERACTION,Homo sapiens
19,CHEMBL5465557,CCN2-EGFR,PROTEIN-PROTEIN INTERACTION,Homo sapiens